version: '3.9'
services:
  web:
    build: .
    image: tasksapp
    container_name: tasksapp_ready
    ports:
      - "7288:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
